argument_specs:
  main:
    options:
      cloudkit_cluster_templates:
        type: list
        description: Cluster templates to publish to the cluster_templates endpoint
      cloudkit_vm_templates:
        type: list
        description: VM templates
      cloudkit_fulfillment_service_uri:
        type: str
        required: true
      cloudkit_fulfillment_service_token:
        type: str
        required: true
      publish_templates_cluster_api_endpoint:
        type: str
        description: API endpoint for cluster templates
        default: "{{ cloudkit_fulfillment_service_uri }}/api/private/v1/cluster_templates"
      publish_templates_vm_api_endpoint:
        type: str
        description: API endpoint for VM templates
        default: "{{ cloudkit_fulfillment_service_uri }}/api/private/v1/virtual_machine_templates"
