apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: cloudkit-aap-base

resources:
  - aap.yaml
  - cloudkit-sa.yaml
  - job.yaml
  - template-publisher.yaml

labels:
- pairs:
    cloudkit.openshift.io/project: cloudkit-aap
