- name: Enumerate cluster templates
  ansible.builtin.set_fact:
    cloudkit_cluster_templates: "{{ cloudkit_template_collections | cloudkit.service.find_cluster_template_roles }}"

- name: Enumerate ComputeInstance templates
  ansible.builtin.set_fact:
    cloudkit_compute_instance_templates: "{{ cloudkit_template_collections | cloudkit.service.find_compute_instance_template_roles }}"
