- name: Enumerate cluster templates
  ansible.builtin.set_fact:
    cloudkit_cluster_templates: "{{ cloudkit_template_collections | cloudkit.service.find_cluster_template_roles }}"

- name: Enumerate VM templates
  ansible.builtin.set_fact:
    cloudkit_vm_templates: "{{ cloudkit_template_collections | cloudkit.service.find_vm_template_roles }}"
