argument_specs:
  create_subnet:
    options:
      network_id:
        description: |
          ID of the network associated with the subnet
        type: "str"
        required: true
      subnet_name:
        description: |
          Name of the subnet to be created
        type: "str"
        required: true
      l3_network_tags:
        description: |
          List of tags to apply to the subnet and router
        type: "list"
        required: false
  destroy_subnet:
    options:
      subnet_name:
        description: |
          Name or ID of the subnet to be destroyed
        type: "str"
        required: true
  get_subnet:
    options:
      subnet_name:
        description: |
          Name or ID of the subnet to be destroyed
        type: "str"
        required: true
  create_router:
    options:
      router_name:
        description: |
          Name of the router to be created
        type: "str"
        required: true
      router_subnets:
        description: |
          List of names or IDs of the subnets to attach to the router
        type: "list"
        required: false
  destroy_router:
    options:
      router_name:
        description: |
          Name or ID of the router to be destroyed
        type: "str"
        required: true
  list_routers:
    options:
      l3_network_properties:
        description: |
          Dictionary of properties to convert to tags for filtering routers
        type: "dict"
        required: false
  list_subnets:
    options:
      l3_network_properties:
        description: |
          Dictionary of properties to convert to tags for filtering subnets
        type: "dict"
        required: false
