---
# Network Configuration Defaults
default_vm_internal_network: "hypershift"

# Storage Defaults
default_vm_storage_class: "nfs-client"  # NFS storage operator storage class

# Labels applied to all VM resources
default_vm_labels: "{{ {vm_order_label: vm_order_name} }}"

cloud_init_config_default: "{{ '#cloud-config' | b64encode }}"
