---
current_namespace: "{{ lookup('env', 'NAMESPACE') }}"
aap_instance_name: "{{ lookup('env', 'AAP_INSTANCE_NAME', default='innabox-aap') }}"
aap_hostname: "{{ lookup('env', 'AAP_HOSTNAME', default='http://' + aap_instance_name) }}"
aap_username: "{{ lookup('env', 'AAP_USERNAME', default='admin') }}"
aap_password: "{{ lookup('env', 'AAP_PASSWORD', default=Undefined) }}"
aap_validate_certs: "{{ lookup('env', 'AAP_VALIDATE_CERTS', default='true') | bool }}"
aap_organization_name: "{{ lookup('env', 'AAP_ORGANIZATION_NAME', default='innabox') }}"
aap_project_name: "{{ lookup('env', 'AAP_PROJECT_NAME', default=current_namespace) }}"
aap_prefix: "{{ lookup('env', 'AAP_PREFIX', default=aap_organization_name + '-' + aap_project_name) }}"
aap_project_git_uri: "{{ lookup('env', 'AAP_PROJECT_GIT_URI', default='https://github.com/innabox/cloudkit-aap.git') }}"
aap_project_git_branch: "{{ lookup('env', 'AAP_PROJECT_GIT_BRANCH', default='main') }}"
aap_ee_image: "{{ lookup('env', 'AAP_EE_IMAGE', default='ghcr.io/innabox/cloudkit-aap:latest') }}"
license_manifest_path: "{{ lookup('env', 'LICENSE_MANIFEST_PATH', default='/var/secrets/config-as-code-manifest/license.zip') }}"
