cluster_order_label: "cloudkit.openshift.io/clusterorder"
cluster_order_infrastructure_finalizer: "cloudkit.openshift.io/infrastructure"

compute_instance_label: "cloudkit.openshift.io/computeinstance"
compute_instance_cloudkit_finalizer: "cloudkit.openshift.io/computeinstance-aap"

hostpool_label: "cloudkit.openshift.io/hostpool"
hostpool_infrastructure_finalizer: "cloudkit.openshift.io/infrastructure"

host_label: "cloudkit.openshift.io/host"
host_infrastructure_finalizer: "cloudkit.openshift.io/infrastructure"
host_uuid_label: "cloudkit.openshift.io/host-uuid"
