cluster_order_label: "cloudkit.openshift.io/clusterorder"
cluster_order_infrastructure_finalizer: "cloudkit.openshift.io/infrastructure"

compute_instance_label: "cloudkit.openshift.io/computeinstance"
compute_instance_cloudkit_finalizer: "cloudkit.openshift.io/computeinstance-aap"
