argument_specs:
  main:
    options:
      cluster_order:
        type: dict
        required: true
      cluster_working_namespace:
        type: str
        required: true
      node_requests:
        type: list
        elements: dict
        options:
          numberOfNodes:
            type: int
            required: true
          resourceClass:
            type: str
            required: true
            choices:
              - fc430
      template_parameters:
        type: dict
        options:
          fail_install:
            type: bool
            required: false
          fail_post_install:
            type: bool
            required: false
          fail_delete:
            type: bool
            required: false
