# Define the display name and description of the template
title: Test template
description: >
  This template does nothing and is intended only for development and testing.

# This sets the nodeRequest field in the ClusterOrder manifest. There must be at
# least one entry in this list.
default_node_request:
  - resourceClass: none
    numberOfNodes: 1

# This declares that for a cluster built from this template, only the resource
# classes listed here may be used when requesting additional nodes. If this
# list is empty or unspecified, a ClusterOrder may request nodes from any
# available resource class.
allowed_resource_classes: []
