argument_specs:
  main:
    options:
      cluster_order:
        type: dict
        required: true
      cluster_working_namespace:
        type: str
        required: true
      node_requests:
        type: list
        elements: dict
        options:
          numberOfNodes:
            type: int
            required: true
          resourceClass:
            type: str
            required: true
      template_parameters:
        type: dict
        options:
          pull_secret:
            description: >
              The pull secret contains credentials for authenticating to image repositories.
            type: str
            required: true
          ssh_public_key:
            description: >
              A public ssh key that will be installed into the `authorized_keys` file
              of the `core` user on cluster worker nodes.
            type: str
