- name: Check if network exists
  openstack.cloud.networks_info:
    name: "{{ network_name }}"
  register: networks

- name: Set create_network_result to found network
  when: networks.networks
  ansible.builtin.set_fact:
    create_network_result: "{{ networks.networks[0].id }}"

- name: Create a new network
  when: not networks.networks
  block:
  - name: Create network  # noqa:no-changed-when
    ansible.builtin.command: >-
      openstack network create {% for tag in l2_network_tags %}--tag "{{ tag }}" {% endfor %}--mtu "{{ l2_network_mtu }}" "{{ network_name }}" -f json
    register: network_cmd_result

  - name: Set create_network_result to new network
    ansible.builtin.set_fact:
      create_network_result: "{{ (network_cmd_result.stdout | from_json).id }}"
