---
publish_templates_cluster_api_endpoint: "{{ cloudkit_fulfillment_service_uri }}/api/private/v1/cluster_templates"
publish_templates_compute_instance_api_endpoint: "{{ cloudkit_fulfillment_service_uri }}/api/private/v1/compute_instance_templates"
