argument_specs:
  main:
    options:
      hosted_cluster_state:
        type: str
        required: true
        choices:
        - present
        - absent
      hosted_cluster_name:
        type: str
        required: true
      hosted_cluster_namespace:
        type: str
        required: true
      hosted_cluster_node_requests:
        type: list
        elements: dict
        suboptions:
          number_of_nodes:
            type: int
            required: true
          resource_class:
            type: str
            required: true
      hosted_cluster_settings:
        type: dict
        required: true
        options:
          ocp_release_image:
            type: str
            required: true
          pull_secret:
            type: str
            required: true
          ssh_public_key:
            type: str
            required: false
