argument_specs:
  add_host_to_hostpool:
    options:
      host_pool_name:
        description: Hostpool to add host to
        type: "str"
        required: true
      host_name:
        description: Host to add to hostpool
        type: "str"
        required: true
  attach_host_to_network:
    options:
      host_name:
        description: Host name
        type: "str"
        required: true
      host_network:
        description: Network name
        type: "str"
        required: true
  clean_host:
    options:
      host_name:
        description: Host name
        type: "str"
        required: true
  get_host:
    options:
      host_uid:
        description: Host UID
        type: "str"
        required: true
  list_hosts:
    options:
      host_class:
        description: Host class to filter hosts by
        type: "str"
        required: false
      host_pool_name:
        description: Hostpool to filter hosts by
        type: "str"
        required: false
  list_host_classes_for_hostpool:
    options:
      host_pool_name:
        description: Hostpool to check
        type: "str"
        required: true
  remove_host_from_hostpool:
    options:
      host_name:
        description: Host to remove from hostpool
        type: "str"
        required: true
  sync_host_power_state:
    options:
      host_uid:
        description: Host UID
        type: "str"
        required: true
      host_target_power_state:
        description: Target power state
        type: "str"
        required: true
