- name: Extract template id
  when: >-
    template_id is not defined
  ansible.builtin.set_fact:
    template_id: "{{ compute_instance.spec.templateID }}"

- name: Extract template parameters
  when: >-
    template_parameters is not defined
  ansible.builtin.set_fact:
    template_parameters: "{{ compute_instance.spec.templateParameters | from_json }}"
